package clases;
// Generated 27 nov. 2023 16:49:50 by Hibernate Tools 4.3.1



/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int numDepartamento;
     private String nomeDepartamento;

    public Departamento() {
    }

    public Departamento(int numDepartamento, String nomeDepartamento) {
       this.numDepartamento = numDepartamento;
       this.nomeDepartamento = nomeDepartamento;
    }
   
    public int getNumDepartamento() {
        return this.numDepartamento;
    }
    
    public void setNumDepartamento(int numDepartamento) {
        this.numDepartamento = numDepartamento;
    }
    public String getNomeDepartamento() {
        return this.nomeDepartamento;
    }
    
    public void setNomeDepartamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }




}


