package clases;
// Generated 27 nov. 2023 16:49:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empregado generated by hbm2java
 */
public class Empregado  implements java.io.Serializable {


     private String nss;
     private String nome;
     private String apelido1;
     private String apelido2;
     private Float salario;
     private Date dataNacemento;
     private char sexo;

    public Empregado() {
    }

	
    public Empregado(String nss, String nome, String apelido1, char sexo) {
        this.nss = nss;
        this.nome = nome;
        this.apelido1 = apelido1;
        this.sexo = sexo;
    }
    public Empregado(String nss, String nome, String apelido1, String apelido2, Float salario, Date dataNacemento, char sexo) {
       this.nss = nss;
       this.nome = nome;
       this.apelido1 = apelido1;
       this.apelido2 = apelido2;
       this.salario = salario;
       this.dataNacemento = dataNacemento;
       this.sexo = sexo;
    }
   
    public String getNss() {
        return this.nss;
    }
    
    public void setNss(String nss) {
        this.nss = nss;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido1() {
        return this.apelido1;
    }
    
    public void setApelido1(String apelido1) {
        this.apelido1 = apelido1;
    }
    public String getApelido2() {
        return this.apelido2;
    }
    
    public void setApelido2(String apelido2) {
        this.apelido2 = apelido2;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public Date getDataNacemento() {
        return this.dataNacemento;
    }
    
    public void setDataNacemento(Date dataNacemento) {
        this.dataNacemento = dataNacemento;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }




}


